name: CodeCov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
