name: Deploy

on:
  push:
    branches: [ ci ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.ENV }} > .env
    - run: echo ${{ secrets.ENV_DB }} > .env.db
    - run: echo ${{ secrets.MASTER_KEY }} > config/master.key

    # - name: stop docker compose
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: 

    - name: Deploy to staging
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: false
        deploy_path: ~/staging/
        stack_file_name: docker-compose.yaml
        keep_files: 5
