name: Deploy

on:
  push:
    branches: [ ci ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.ENV }} > .env
    - run: echo ${{ secrets.ENV_DB }} > .env.db
    - run: echo ${{ secrets.MASTER_KEY }} > config/master.key

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        docker_compose_prefix: staging
